version: "3.3"
services:
  backend: &python
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - '8000:8000'
    volumes:
      - ./:/app
    command: python src/server.py
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  db:
    image: postgres:latest
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    command: streamlit run streamlit/main.py
