version: "3.3"
services:
  backend: &python
    restart: unless-stopped
    # env_file:
    #   - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - '8000:8000'
      # - "${DOCKER_EXPOSE_PORT:-8000}:8081"
    volumes:
      - ./:/app
    command: python src/server.py
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  db:
    image: postgres:latest
    restart: unless-stopped
    # env_file:
    #   - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data:
