"""empty message

Revision ID: 6e31219c16db
Revises: d55449b5fb4e
Create Date: 2023-07-02 15:27:39.457216

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = '6e31219c16db'
down_revision = 'd55449b5fb4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'education')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('education', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
