"""empty message

Revision ID: 409ee93b59f2
Revises: fde71ccac81d
Create Date: 2023-07-02 15:20:48.695891

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = '409ee93b59f2'
down_revision = 'fde71ccac81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
