"""empty message

Revision ID: 49c2810c8e46
Revises: f8f6274d2b22
Create Date: 2023-07-02 16:58:09.893527

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = '49c2810c8e46'
down_revision = 'f8f6274d2b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobdesc', sa.Column('data', sa.String(), nullable=True))
    op.drop_column('jobdesc', 'skills')
    op.drop_column('jobdesc', 'jobbreif')
    op.drop_column('jobdesc', 'responsibilities')
    op.drop_column('jobdesc', 'requirements')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobdesc', sa.Column('requirements', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobdesc', sa.Column('responsibilities', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobdesc', sa.Column('jobbreif', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobdesc', sa.Column('skills', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('jobdesc', 'data')
    # ### end Alembic commands ###
