"""empty message

Revision ID: 0a58311f8842
Revises: ed51251c62f3
Create Date: 2023-07-02 14:40:22.241399

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = '0a58311f8842'
down_revision = 'ed51251c62f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
