"""empty message

Revision ID: d55449b5fb4e
Revises: 409ee93b59f2
Create Date: 2023-07-02 15:23:22.294160

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd55449b5fb4e'
down_revision = '409ee93b59f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'education',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('file', 'projects',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('file', 'achievements',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('file', 'skills',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'skills',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('file', 'achievements',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('file', 'projects',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('file', 'education',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
