"""empty message

Revision ID: b9227244d6e0
Revises: 6e31219c16db
Create Date: 2023-07-02 15:28:35.675934

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = 'b9227244d6e0'
down_revision = '6e31219c16db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('education', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'education')
    # ### end Alembic commands ###
