"""empty message

Revision ID: f8f6274d2b22
Revises: 01705a7a2999
Create Date: 2023-07-02 16:36:28.175009

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f8f6274d2b22'
down_revision = '01705a7a2999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jobdesc_filename_key', 'jobdesc', type_='unique')
    op.drop_column('jobdesc', 'filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobdesc', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('jobdesc_filename_key', 'jobdesc', ['filename'])
    # ### end Alembic commands ###
