"""empty message

Revision ID: 29cffd7ef6b9
Revises: 0a58311f8842
Create Date: 2023-07-02 14:43:30.221844

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29cffd7ef6b9'
down_revision = '0a58311f8842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('meta', sa.JSON(), nullable=True))
    op.drop_column('file', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('file', 'meta')
    # ### end Alembic commands ###
