"""empty message

Revision ID: 4e2add072b89
Revises: ff42e65bc21b
Create Date: 2023-08-10 16:12:58.011781

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = '4e2add072b89'
down_revision = 'ff42e65bc21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
