"""empty message

Revision ID: 9ea53e734e62
Revises: 954c2272315c
Create Date: 2023-07-02 15:36:09.779140

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = '9ea53e734e62'
down_revision = '954c2272315c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
