"""empty message

Revision ID: 954c2272315c
Revises: b9227244d6e0
Create Date: 2023-07-02 15:33:55.713766

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = '954c2272315c'
down_revision = 'b9227244d6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
