"""empty message

Revision ID: 9bc37c04dd6b
Revises: 29cffd7ef6b9
Create Date: 2023-07-02 14:44:42.085155

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bc37c04dd6b'
down_revision = '29cffd7ef6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('data', sa.JSON(), nullable=True))
    op.drop_column('file', 'meta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('file', 'data')
    # ### end Alembic commands ###
