"""empty message

Revision ID: fde71ccac81d
Revises: 9bc37c04dd6b
Create Date: 2023-07-02 14:58:27.470419

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fde71ccac81d'
down_revision = '9bc37c04dd6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('education', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('file', sa.Column('projects', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('file', sa.Column('achievements', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('file', sa.Column('skills', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('file', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('file', 'skills')
    op.drop_column('file', 'achievements')
    op.drop_column('file', 'projects')
    op.drop_column('file', 'education')
    # ### end Alembic commands ###
