"""empty message

Revision ID: 8a71905a2a93
Revises: 49c2810c8e46
Create Date: 2023-07-02 17:19:24.133930

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = '8a71905a2a93'
down_revision = '49c2810c8e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('data', sa.String(), nullable=True))
    op.drop_column('file', 'achievements')
    op.drop_column('file', 'experience')
    op.drop_column('file', 'projects')
    op.drop_column('file', 'skills')
    op.drop_column('file', 'education')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('education', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('file', sa.Column('skills', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('file', sa.Column('projects', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('file', sa.Column('experience', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('file', sa.Column('achievements', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('file', 'data')
    # ### end Alembic commands ###
